spring:
  redis:
    database: 0
    host: 127.0.0.1
    password:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wuguangnuo5?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 10000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      filters:
        - stat
        - wall
        - log4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        exclusions:
          #          - "*.js"
          #          - "*.gif"
          #          - "*.jpg"
          #          - "*.png"
          #          - "*.css"
          #          - "*.ico"
          - "/druid/*"
          - "/urule/*"
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
urule:
  repository:
    databasetype: mysql
    datasourcename: datasource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: /wuguangnuo/wgn.cn/website/init/logback-spring.xml
  level:
    cn.wgn.website: debug
    cn.wgn.framework: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error
server:
  port: 8800

private-config:
  # 腾讯COS配置
  cos:
    secret-id: A********************************9
    secret-key: C******************************Q
    bucket-name: w*******************7
    region-name: a**********u
  # 腾讯AI配置
  tencent-ai:
    app-id: 2********8
    app-key: 2**************U
  # 邮箱配置
  mail:
    ssl-factory: javax.net.ssl.SSLSocketFactory
    smtp-server: smtp.***.com
    port: 465
    from-user-name: 123@email.com
    from-user-password: 123456
    copy-to: wuguangnuo@qq.com
  # IP地址库
  ip2region: /wuguangnuo/wgn.cn/website/src/main/resources/ip2region.db
  # token 配置
  token:
    # 令牌密钥
    secret: wuguangnuo.cn
    # 令牌有效期（单位分钟）
    expireTime: 60
